
###
POST http://localhost:8080/api/glossary/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="sample_glossary.csv"
Content-Type: text/csv

< ./sample_glossary.csv

###
GET http://localhost:8080/api/glossary/search?
    query=java&
    limit=5